# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kaykin <kaykin@student.42istanbul.com.t    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/02 14:29:11 by kaykin            #+#    #+#              #
#    Updated: 2024/05/25 13:15:31 by kaykin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:= libft.a
CC		:= gcc
CFLAGS	:= -Wall -Wextra -Werror
FILES	:= ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c \
				ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c \
				ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c \
				ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
				ft_printf/ft_printf.c ft_printf/ft_numbers.c ft_printf/ft_words.c gnl/ft_getnextline.c gnl/ft_gnl_utils.c
				
OBJ		:= $(FILES:.c=.o)

BSRC	:= ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c \
        		ft_lstmap.c
B_OBJ	:= $(BSRC:.c=.o)

all: $(NAME)

$(NAME) : $(OBJ)
			ar -rc $(NAME) $(OBJ)

bonus: $(OBJ) $(B_OBJ)
			ar -rc $(NAME) $(OBJ) $(B_OBJ)

clean:
			rm -f $(OBJ) $(B_OBJ)

fclean: clean
			rm -f $(NAME)

re: fclean all

.PHONY: all bonus clean fclean re